name: Build

on:
  push:
    branches: 
      - master
      - test
    paths-ignore:
      - '*.md'
      - '**/.gitignore'
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Xzonn/STRAHChsLocalizationHelper
          ref: master
          submodules: recursive
      - uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.9,)'
      - name: Cache FBX SDK
        id: cache-fbx-sdk
        uses: actions/cache@v4
        with:
          path: bin/fbx
          key: fbx-2020-3-4-vs2022
      - name: Download FBX SDK
        if: steps.cache-fbx-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir "bin"
          mkdir "bin/fbx/"
          Push-Location -Path "bin/fbx/"
          Invoke-WebRequest -Uri "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_vs2022_win.exe" -OutFile "fbxsdk.exe"
          Invoke-WebRequest -Uri "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-3-4/fbx202034_fbxsdk_vs2022_pdbs.exe" -OutFile "fbxpdb.exe"
          Pop-Location
      - name: Install dependencies
        run: |
          Start-Process -FilePath "bin/fbx/fbxsdk.exe" /S -Wait
          Start-Process -FilePath "bin/fbx/fbxpdb.exe" /S -Wait
          nuget restore
      - name: Build
        run: |
          msbuild /t:AssetStudioFBXNative /p:Configuration=Release /p:Platform=x64 /verbosity:minimal
          msbuild /t:Texture2DDecoderNative /p:Configuration=Release /p:Platform=x64 /verbosity:minimal
          msbuild /t:STRAHChsLocalizationHelper:publish /p:Configuration=Release /p:Platform=x64 /verbosity:minimal
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: STRAHChsLocalizationHelper
          path: STRAHChsLocalizationHelper/bin/Release/net8.0-windows/win-x64/publish/
